apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-canary
  template:
    metadata:
      labels:
        app: app-canary
    spec:
      containers:
      - name: app-canary
        image: myregistry.com/devsecops:canary
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: app-canary
spec:
  type: LoadBalancer
  selector:
    app: app-canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8090
